services:
  book-service-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book-db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/book-postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - app-net

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
    networks:
      - app-net
    volumes:
      - ./docker/redis:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP port for apps
      - "15672:15672"    # HTTP UI for management
    volumes:
      - ./docker/rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'

  club-service-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=club-db
    ports:
      - "5433:5432"
    volumes:
      - ./docker/club-postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - app-net

  event-service-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event-db
    ports:
      - "5434:5432"
    volumes:
      - ./docker/event-postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - app-net

networks:
  app-net:
    external: true