services:
  book-service-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book-db
    ports:
      - "5432:5432"
    networks:
      - app-net

networks:
  app-net:
    external: true