services:

  book-service:
    image: alexmercer1234556789/book-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "4001:4001"
    restart: always
    networks:
      - app-net

  club-service:
    image: alexmercer1234556789/club-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "4002:4002"
    restart: always
    networks:
      - app-net


networks:
  app-net:
    external: true