services:
  book-service-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=book-db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'
    networks:
      - app-net

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: password
    networks:
      - app-net
    volumes:
      - ./docker/redis:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'

networks:
  app-net:
    external: true