apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: book-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: alexmercer1234556789/book-service
          ports:
            - containerPort: 4001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker