apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: book-app
spec:
  type: ClusterIP
  selector:
    app: book-service
  ports:
    - port: 4001
      targetPort: 4001
      protocol: TCP