apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-service-ingress
  namespace: book-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: book-club.com
      http:
        paths:
          - path: /book-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: book-service
                port:
                  number: 4001
          - path:  /club-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: club-service
                port:
                  number: 4002
          - path:  /event-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: event-service
                port:
                  number: 4003