apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: book-app
spec:
  type: ClusterIP
  selector:
    app: event-service
  ports:
    - port: 4003
      targetPort: 4003
      protocol: TCP