spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://book-service-db:5432/book-db
    username: postgres
    password: postgres
  data:
    redis:
      host: redis
  rabbitmq:
    host: rabbitmq
server:
  port: 4001