apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-db
  namespace: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service-db
  template:
    metadata:
      labels:
        app: book-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: book-db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: book-postgres-pvc