apiVersion: v1
kind: Service
metadata:
  name: club-service
  namespace: book-app
spec:
  type: ClusterIP
  selector:
    app: club-service
  ports:
    - port: 4002
      targetPort: 4002
      protocol: TCP